name: docker

on:
  push:
    tags: ["v*.*.*"]           # релизы по тегам vX.Y.Z
    branches: ["dev"]          # опционально: собирать dev-образы
  workflow_dispatch:           # ручной запуск из Actions

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write          # доступ к GHCR
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            # релизные теги
            type=ref,event=tag
            # короткий sha
            type=sha,format=short,prefix=sha-
            # latest только на теги
            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/tags/v') }}
            # dev-теги при пуше в ветку dev
            type=raw,value=dev,enable=${{ github.ref == 'refs/heads/dev' }}
            type=sha,format=short,prefix=dev-,enable=${{ github.ref == 'refs/heads/dev' }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            APP_VERSION=${{ startsWith(github.ref, 'refs/tags/v') && github.ref_name || (github.ref == 'refs/heads/dev' && 'dev' || 'ci') }}
            GIT_SHA=${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
