name: tests
on:
  push:
  pull_request:
  workflow_dispatch:  # даёт кнопку “Run workflow” в UI

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.11', '3.12']

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Upgrade pip
        run: python -m pip install -U pip

      # Установка зависимостей (если есть requirements.txt — используем его),
      # плюс гарантированно ставим pytest-cov для покрытия.
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install "pytest>=7,<9" pandas pyyaml
          fi
          pip install pytest-cov

      # Запуск тестов с подсчётом покрытия и генерацией coverage.xml
      - name: Run tests with coverage
        run: pytest --cov=src --cov-report=xml -q

      # Прикладываем coverage.xml как артефакт к ран-логу
      - name: Upload coverage.xml
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.python-version }}
          path: coverage.xml
